from typing import List

from aiohttp import ClientSession

from consts.api_consts import CREATE_PLAYLIST_URL_FORMAT, ADD_PLAYLIST_ITEMS_URL_FORMAT
from consts.data_consts import ID
from data_collection.spotify.spotify_scope import SpotifyScope
from tools.environment_manager import EnvironmentManager
from utils.spotify_utils import build_spotify_headers


class PlaylistsCreator:
    async def create(self, uris: List[str], public: bool, user_id: str):
        EnvironmentManager().set_env_variables()
        playlist_id = await self._create_playlist(public, user_id)
        valid_uris = [uri for uri in uris if isinstance(uri, str)]
        await self._add_playlist_items(playlist_id, valid_uris)

    async def _create_playlist(self, public: bool, user_id: str) -> str:
        url = CREATE_PLAYLIST_URL_FORMAT.format(user_id)
        body = {
            "name": "My second automatic playlist",
            "description": "Generated by playlist.ai",
            "public": public
        }

        async with self._session.post(url=url, json=body) as raw_response:
            response = await raw_response.json()

        return response[ID]

    async def _add_playlist_items(self, playlist_id: str, uris: List[str]) -> None:
        url = ADD_PLAYLIST_ITEMS_URL_FORMAT.format(playlist_id)
        body = {
            'uris': uris
        }

        async with self._session.post(url=url, json=body) as raw_response:
            response = await raw_response.json()

    @property
    def _session(self) -> ClientSession:
        headers = build_spotify_headers(
            is_authorization_token=True,
            scopes=(
                SpotifyScope.PLAYLIST_MODIFY_PUBLIC,
                SpotifyScope.PLAYLIST_MODIFY_PRIVATE
            )
        )

        return ClientSession(headers=headers)
