TOKEN_REQUEST_URL = "https://accounts.spotify.com/api/token"
AUDIO_FEATURES_URL_FORMAT = "https://api.spotify.com/v1/audio-features/{}"
TRACKS_URL_FORMAT = 'https://api.spotify.com/v1/tracks/{}'
ARTISTS_ALBUMS_URL_FORMAT = 'https://api.spotify.com/v1/artists/{}/albums?offset=0&limit=20&include_groups=album,single,compilation,appears_on'
PLAYLIST_URL_FORMAT = 'https://api.spotify.com/v1/playlists/{}'
ARTISTS_URL_FORMAT = 'https://api.spotify.com/v1/artists?ids={}'
CREATE_PLAYLIST_URL_FORMAT = 'https://api.spotify.com/v1/users/{}/playlists'
ADD_PLAYLIST_ITEMS_URL_FORMAT = 'https://api.spotify.com/v1/playlists/{}/tracks'
AUTHORIZATION_REQUEST_URL_FORMAT = 'https://accounts.spotify.com/authorize?{}'
CLIENT_ID = 'client_id'
RESPONSE_TYPE = 'response_type'
REDIRECT_URI = 'redirect_uri'
SCOPE = 'scope'
CODE = 'code'
GRANT_TYPE = 'grant_type'
JSON = 'json'
ACCESS_TOKEN = 'access_token'
AIO_POOL_SIZE = 5
