from consts.aggregation_consts import MIN, MAX, MEDIAN, FIRST, COUNT, SUM
from consts.audio_features_consts import KEY, DANCEABILITY, ENERGY, LOUDNESS, MODE, SPEECHINESS, ACOUSTICNESS, \
    INSTRUMENTALNESS, LIVENESS, VALENCE, TEMPO
from consts.data_consts import SONG, ARTIST_ID, ERROR, ANALYSIS_URL, TRACK_HREF, URI, ID, TYPE, SCRAPED_AT, SNAPSHOT_ID, \
    STATION, RELEASE_DATE, MAIN_ALBUM, MAIN_GENRE, GENRES, ARTIST_NAME, ADDED_AT, NAME, FOLLOWERS, BROADCASTING_YEAR, \
    POPULARITY, TRACK_NUMBER, DURATION_MS, EXPLICIT, ARTIST_FOLLOWERS, ARTIST_POPULARITY, ALBUM_TRACKS_NUMBER, \
    IS_ISRAELI, TIME_SIGNATURE
from consts.language_consts import LANGUAGE, SCORE
from consts.spotify_albums_details_consts import MEDIAN_MARKETS_NUMBER, FIRST_ALBUM_RELEASE_YEAR, \
    LAST_ALBUM_RELEASE_YEAR, YEARS_ACTIVE, APPEARS_ON_SINGLES_COUNT, APPEARS_ON_COMPILATIONS_COUNT, \
    APPEARS_ON_ALBUMS_COUNT, SINGLES_COUNT, COMPILATIONS_COUNT, ALBUMS_COUNT
from data_processing.pre_processors.language_pre_processor import SHAZAM_KEY, SHAZAM_ADAMID

NON_NUMERIC_COLUMNS = [
    NAME,
    ADDED_AT,
    ARTIST_NAME,
    GENRES,
    MAIN_ALBUM,
    RELEASE_DATE,
    SNAPSHOT_ID,
    SCRAPED_AT,
    TYPE,
    ID,
    URI,
    TRACK_HREF,
    ANALYSIS_URL,
    ERROR,
    ARTIST_ID
]

IRRELEVANT_COLUMNS = [
    FOLLOWERS,
    SHAZAM_KEY,
    SHAZAM_ADAMID,
    BROADCASTING_YEAR,
    GENRES
]

DROPPABLE_COLUMNS = NON_NUMERIC_COLUMNS + IRRELEVANT_COLUMNS

CATEGORICAL_COLUMNS_AGGREGATION_MAPPING = {
    LANGUAGE: [FIRST],
    KEY: [FIRST],
    MAIN_GENRE: [FIRST],
    STATION: [SUM]
}
CATEGORICAL_COLUMNS = list(CATEGORICAL_COLUMNS_AGGREGATION_MAPPING.keys())

GROUPBY_COLUMNS = [
    SONG
]

GROUPBY_FIRST_COLUMNS = [
    TRACK_NUMBER,
    DURATION_MS,
    EXPLICIT,
    ALBUM_TRACKS_NUMBER,
    IS_ISRAELI,
    DANCEABILITY,
    ENERGY,
    LOUDNESS,
    MODE,
    SPEECHINESS,
    ACOUSTICNESS,
    INSTRUMENTALNESS,
    LIVENESS,
    VALENCE,
    TEMPO,
    TIME_SIGNATURE,
    SCORE,
    MEDIAN_MARKETS_NUMBER,
    FIRST_ALBUM_RELEASE_YEAR,
    LAST_ALBUM_RELEASE_YEAR,
    YEARS_ACTIVE,
    ALBUMS_COUNT,
    COMPILATIONS_COUNT,
    SINGLES_COUNT,
    APPEARS_ON_ALBUMS_COUNT,
    APPEARS_ON_COMPILATIONS_COUNT,
    APPEARS_ON_SINGLES_COUNT
]

GROUPBY_MIN_MAX_MEDIAN_COLUMNS = [
    POPULARITY,
    ARTIST_FOLLOWERS,
    ARTIST_POPULARITY
]
